BOARD ?= nucleo32-l031

RIOTBASE=../../RIOT

include ../../RIOT/tests/Makefile.tests_common

FEATURES_REQUIRED = periph_adc

USEMODULE += xtimer
USEMODULE += printf_float

include $(RIOTBASE)/Makefile.include
