BOARD ?= nucleo-l152
include /home/inria/Descargas/RIOT-scripts/Tutorials/RIOT/tests/Makefile.tests_common

FEATURES_REQUIRED = periph_adc
USEMODULE += xtimer

include /home/inria/Descargas/RIOT-scripts/Tutorials/RIOT/Makefile.include
