BOARD ?= nucleo32-l031
include ../../RIOT/tests/Makefile.tests_common

RIOTBASE=../../RIOT

FEATURES_REQUIRED = periph_adc

USEMODULE += xtimer
USEMODULE += printf_float

include $(RIOTBASE)/Makefile.include
